Repository visualbis/exceljs, pull requests merged in 2023-11, with the labels that each got.

#26 fix: add image
  lib/doc/anchor.js
  lib/doc/image.js
  lib/doc/workbook.js
  lib/doc/worksheet.js
  lib/utils/u-zip.js
  lib/xlsx/xform/book/workbook-xform.js
  lib/xlsx/xform/core/content-types-xform.js
  lib/xlsx/xform/drawing/base-cell-anchor-xform.js
  lib/xlsx/xform/drawing/one-cell-anchor-xform.js
  lib/xlsx/xform/drawing/two-cell-anchor-xform.js
  lib/xlsx/xform/sheet/worksheet-xform.js
  lib/xlsx/xlsx.js
  package.json
Labels: enhancement

#27 chore: version bump
  package.json
Labels: Other

#28 fix(build): unwanted package remvoed
  package.json
Labels: Refactoring

#29 fix(build):npm publish
  lib/doc/image.js
Labels: Bug fix

#30 npm publish
  .browserslistrc
  .circleci/config.yml
Labels: Refactoring
